const PRODUCT_PRICE_LIST_REQUEST = 'PRODUCT_PRICE_LIST_REQUEST';
const PRODUCT_PRICE_LIST_SUCCESS = 'PRODUCT_PRICE_LIST_SUCCESS';
const PRODUCT_PRICE_LIST_FAILURE = 'PRODUCT_PRICE_LIST_FAILURE';

const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE';

const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE ';

const types = {
  PRODUCT_PRICE_LIST_REQUEST,
  PRODUCT_PRICE_LIST_SUCCESS,
  PRODUCT_PRICE_LIST_FAILURE,
  ADD_PRODUCT_REQUEST,
  ADD_PRODUCT_SUCCESS,
  ADD_PRODUCT_FAILURE,
  EDIT_PRODUCT_REQUEST,
  EDIT_PRODUCT_SUCCESS,
  EDIT_PRODUCT_FAILURE,
  DELETE_PRODUCT_REQUEST,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_FAILURE
};

export default types;
